extends Node

signal monodialog_finished(branch_type)

signal cangkir_interaction_requested
signal drawer_interaction_requested
signal padlock_interaction_requested
signal bathtub_interaction_requested
signal padlock_unlocked(item_inside: ItemData)
